### ISSUE TITLE
No anno["segmentation"] when processing MP6D datasets

### ISSUE THREAD

**Issue by zxl55552** [AI-Application-and-Integration-Lab/RDPN6D#2]
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/my-env/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/envs/my-env/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/my-env/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/autodl-tmp/RDPN/core/gdrn_modeling/../../core/gdrn_modeling/data_loader.py", line 1055, in __getitem__
    processed_data = self.read_data(dataset_dict)
  File "/root/autodl-tmp/RDPN/core/gdrn_modeling/../../core/gdrn_modeling/data_loader.py", line 855, in read_data
    mask_visib = anno["segmentation"].astype("float32") * mask_obj
KeyError: 'segmentation'

**Comment by p458732** [comment]
Hi,
I have updated the code to a new version, and it should be trained successfully without any issues now. 
One thing you may need to do is run "tools/mp6d/gen_mask.py" to generate the mask images for our model training.
